[build-system]
requires = [
    "setuptools >= 40.9.0",
    "wheel",
    "textual-dev"
]
build-backend = "setuptools.build_meta"

[project]
name = "EmpireStateRunUp"
version = "0.0.1"
dependencies = [
    "pandas",
    "textual",
    'importlib-metadata; python_version<"3.8"',
]

[project.scripts]
es_normalizer = "scripts.data_normalizer:main"
5_number = "empirestaterunup.apps:run_5_number"